# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\show_answer_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_question_window(object):
    def setupUi(self, show_answer_window):
        show_answer_window.setObjectName("show_answer_window")
        show_answer_window.resize(1060, 820)
        self.centralwidget = QtWidgets.QWidget(show_answer_window)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1061, 821))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.deck_button = QtWidgets.QPushButton(self.frame)
        self.deck_button.setGeometry(QtCore.QRect(360, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deck_button.setFont(font)
        self.deck_button.setAutoFillBackground(False)
        self.deck_button.setObjectName("deck_button")
        self.add_button = QtWidgets.QPushButton(self.frame)
        self.add_button.setGeometry(QtCore.QRect(470, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.stat_button = QtWidgets.QPushButton(self.frame)
        self.stat_button.setGeometry(QtCore.QRect(630, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stat_button.setFont(font)
        self.stat_button.setObjectName("stat_button")
        self.dark_mode_radio_button = QtWidgets.QRadioButton(self.frame)
        self.dark_mode_radio_button.setGeometry(QtCore.QRect(920, 50, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.dark_mode_radio_button.setFont(font)
        self.dark_mode_radio_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dark_mode_radio_button.setChecked(False)
        self.dark_mode_radio_button.setObjectName("dark_mode_radio_button")
        self.front_text = QtWidgets.QTextEdit(self.frame)
        self.front_text.setGeometry(QtCore.QRect(20, 86, 1021, 650))
        self.front_text.setFrameShape(QtWidgets.QFrame.Panel)
        self.front_text.setObjectName("front_text")

        # self.back_text = QtWidgets.QTextEdit(self.frame)
        # self.back_text.setGeometry(QtCore.QRect(20, 380, 1021, 351))
        # self.back_text.setFrameShape(QtWidgets.QFrame.Panel)
        # self.back_text.setObjectName("back_text")

        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 740, 1051, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.save_changes_button = QtWidgets.QPushButton(self.frame)
        self.save_changes_button.setGeometry(QtCore.QRect(940, 770, 111, 31))
        self.save_changes_button.setObjectName("save_changes_button")
        self.show_answer_button = QtWidgets.QPushButton(self.frame)
        self.show_answer_button.setGeometry(QtCore.QRect(450, 760, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_answer_button.setFont(font)
        self.show_answer_button.setObjectName("show_answer_button")
        show_answer_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(show_answer_window)
        QtCore.QMetaObject.connectSlotsByName(show_answer_window)

    def retranslateUi(self, show_answer_window):
        _translate = QtCore.QCoreApplication.translate
        show_answer_window.setWindowTitle(_translate("show_answer_window", "Anki-RecallHub"))
        self.deck_button.setText(_translate("show_answer_window", "Decks"))
        self.add_button.setText(_translate("show_answer_window", "Add Flash Card"))
        self.stat_button.setText(_translate("show_answer_window", "Stats"))
        self.dark_mode_radio_button.setText(_translate("show_answer_window", "Dark Mode"))
        self.save_changes_button.setText(_translate("show_answer_window", "Save Changes"))
        self.show_answer_button.setText(_translate("show_answer_window", "Show Answer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    show_answer_window = QtWidgets.QMainWindow()
    ui = Ui_show_question_window()
    ui.setupUi(show_answer_window)
    show_answer_window.show()
    sys.exit(app.exec_())
